<?php echo $this->doctype(). PHP_EOL ?>
    <head>
        <!-- Meta -->
        <?php $this->headTitle()->setSeparator(' - ');
              $this->headTitle('IP');
              echo $this->headTitle() . PHP_EOL;
              
              $this->headLink()->appendStylesheet('/css/reset.css', 'all');
              $this->headLink()->appendStylesheet('/css/fonts.css', 'all');
              $this->headLink()->appendStylesheet('/css/style.css', 'all');
              echo $this->headLink() . PHP_EOL;
              
              $this->headScript()->appendFile('/js/less-grid-4.js', 'text/javascript');
              echo $this->headScript() . PHP_EOL;
              
              $this->headMeta()->setHttpEquiv('Content-type', 'text/html; charset=ISO-8859-1');
              echo $this->headMeta() . PHP_EOL;
              
        ?>
    </head>

<body id="body">
<div id="top">
	<div id="top_content">
		<div id="logo">
			<h1>IP Formation</h1>
			<h4>Benjamin Volle</h4>
		</div>
	</div>
</div>
<div class="menu">
	<div class="menu_content">
		<ul class="menulist">
			<li class="menu_item"><a href="/" class="top">Home</a></li>
			<li class="menu_item"><a href="/index/about" class="top">About</a></li>	
			<li class="menu_item"><a href="#" class="top">Joker</a></li>
			<li class="menu_item"><a href="http://www.php.net" target="_blank" class="top">PHP.net</a></li>
			<li class="menu_item"><a href="http://github.com" target="_blank" class="top">GitHub</a></li>				
			
		</ul>
	</div>
</div>
<div id="video">
	<div id="video_content">
			<h2>Cours Zend Framework</h2>
			<h3>Avec en plus la pose d'un template</h3>

	</div>
</div>
<div id="content">
	<?php echo $this->layout()->content; ?>
</div>

<div id="bottom">
	<div id="bottom_content">
		<div class="callcenter">
			<p class="call_us" style="color:#e44038;padding-left:30px;">Support 24/7: </p>
			<p class="call_us"><img src="/img/phone.png" alt="phone" />  (045)0205968600 or (045)0205968611</p>
			<p class="call_us"><img src="/img/email.png" alt="email" />  contact@contact.com</p>

		</div>

	</div>
</div>
</body>
</html>

    